#pragma once

#include <liburing.h>

enum {
        LIBURING_RS_BLOCK_URING_CMD_DISCARD = BLOCK_URING_CMD_DISCARD,
        LIBURING_RS_BLOCK_URING_CMD_ZONE_RESET_ALL = BLOCK_URING_CMD_ZONE_RESET_ALL,
};
